### PR TITLE
RI-8106: msgpack datetime deserialization

### LINKED ISSUE #5540: [Bug]: Incorrect message pack deserialization of DateTimeOffset property
**Steps to reproduce** 

```
[MessagePackObject]
public class Class1
{
    [Key(0)]
    public DateTimeOffset Date { get; set; }

    [Key(1)]
    public int X { get; set; }

    [Key(2)]
    public bool Y { get; set; }
}
```

1. Serilize any messagepack object with DateTimeOffset property 
2. Store it on redis
3. Try to read it from redis insights

**Actual behavior** 
Example of incorrect deserialization from redis insights
```
[
  [
    {},
    0
  ],
  534,
  false
]
```

**Expected behavior** Not sure, but something like this
```
[
  "2026-02-24T08:14:32.1234567+00:00",
  534,
  false
]
```
It should be clear what DateTimeOffset is that 

**Additional context** MAC, Redis Insights Version 3.0.3 (3.0.3)

### PR DESCRIPTION
**Pull request by pd-redis**
# What

Fix incorrect MessagePack deserialization of .NET `DateTimeOffset` properties. The `postProcessLz4` function in the msgpack decoder was treating `Date` objects (decoded from the standard msgpack timestamp extension type -1) as plain objects, destroying them into `{}` because `Object.entries(new Date())` returns an empty array.

Extracted an `isPlainObject` guard function that excludes both `Uint8Array` and `Date` instances, preserving timestamps through the post-processing step so they serialize correctly as ISO 8601 strings.

| Before | After |
|--------|-------|
| .NET `DateTimeOffset` values display as `[{}, 0]` | .NET `DateTimeOffset` values display as `["2025-02-24T11:43:36.000Z", 0]` |

# Testing

1. Store a MessagePack-serialized .NET object with a `DateTimeOffset` property in Redis
2. Open RedisInsight, navigate to **Browser**
3. Select the key containing the MessagePack data
4. Choose **Msgpack** format from the value formatter dropdown
5. Verify the `DateTimeOffset` field displays as an ISO 8601 date string instead of `{}`

---

Fixes #5540

---

> [!NOTE]
> **Low Risk**
> Low risk: small change to msgpack post-processing type guard plus targeted tests; main risk is inadvertently skipping recursion for other non-plain object types in decoded payloads.
> 
> **Overview**
> Fixes MsgPack timestamp handling during LZ4 post-processing by introducing an `isPlainObject` guard that *excludes `Date` instances* (in addition to `Uint8Array`), preventing decoded timestamps from being flattened into `{}`.
> 
> Adds decoder tests covering msgpack timestamp ext `-1` decoding (standalone and nested) and a .NET `DateTimeOffset`-style array to ensure dates survive decoding and JSON stringify as ISO strings.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 54a7a97363c6817fd9ff877d9953bd80114fbc67. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: redisinsight/ui/src/utils/formatters/msgpack/decoder.ts [hunk 1]
```diff
@@ -8,6 +8,15 @@ import { isLz4SizeMarker, decompressLz4 } from './lz4'
 // Import extensions module to ensure handlers are registered
 import './extensions'
 
+function isPlainObject(value: unknown): value is Record<string, unknown> {
```
Comment (pawelangelow) [inline redisinsight/ui/src/utils/formatters/msgpack/decoder.ts:11]: let's add tests for this guy

Comment (pd-redis) [reply redisinsight/ui/src/utils/formatters/msgpack/decoder.ts:11]: it is tested, this is internal function used in single place, which is covered with tests :)

Comment (pawelangelow) [reply redisinsight/ui/src/utils/formatters/msgpack/decoder.ts:11]: oh, i didn't see it's not exported
